### ISSUE TITLE
Issues building on Windows using Visual Studio 2019

### ISSUE THREAD

**Issue by wihu** [Macabresoft/Macabre2D#1]
Hi, I'm having issues building on Windows using Visual Studio 2019 (as suggested in the project solution).
The error message says that I need .Net 6 SDK installed, but I found out .Net 6 is not supported on VS 2019.
How do you get around this?

**Comment by wihu** [comment]
I actually managed to build and run using VS 2022 instead, however, it throws an exception in `LayersEditor.axaml.cs`:
```
System.NullReferenceException: 'Object reference not set to an instance of an object.'

Macabresoft.Macabre2D.UI.Common.IProjectService.CurrentProject.get returned null.
```

what did I miss out?

**Comment by macabrett** [comment]
You didn't miss anything, it's just been a while since I created a new project in Macabre2D and there was a bug (I've been working on an existing project for quite a while). I've comitted a fix to the bug you've encountered, but since it crashed during project creation, you may need to delete the Content folder created under Macabre2D before relaunching the editor.

I'd also like to warn you that Macabre2D is a hobby project and I wouldn't recommend using it for anything other than messing around or referencing it. It's highly volatile and I'm not currently developing it with users in mind other than me. That said, it's very cool that someone took the time to download and build Macabre2D so thank you! Let me know if you run into any other issues.

**Comment by wihu** [comment]
Thank you for fixing the issue! And no worries, I don't intend to use it for any serious projects, just curious because I was also tinkering with a similar hobby project, which was to build a game editor on top of MonoGame engine. I noticed yours when investigating on C# UI framework, stumbled upon Avalonia UI and your project was listed [here](https://github.com/AvaloniaCommunity/awesome-avalonia#games-and-game-engines).

I think Macabre2D Editor UI looks nice and clean! Although, after some thoughts, I'd probably do it with IMGUI instead of retained mode GUI.

**Comment by macabrett** [comment]
Oh wow, I had no idea my project was listed anywhere! That's cool. Thanks for checking it out and best of luck with your project!
